

############################## DISCOVER PARAMS ########################
params_model_DSCOVR : 
- ["time", "bx_gse", "by_gse", "bz_gse","fs_4", "fs_5", "fs_6", "fs_7", "fs_8", "fs_9","fs_10", "fs_11", "fs_12", "fs_13", "fs_14", "fs_15",
"fs_16", "fs_17", "fs_18", "fs_19", "fs_20", "fs_21","fs_22", "fs_23", "fs_24", "fs_25", "fs_26", "fs_27",
"fs_28", "fs_29", "fs_30", "fs_31", "fs_32", "fs_33","fs_34", "fs_35", "fs_36", "fs_37", "fs_38", "fs_39",
"fs_40", "fs_41", "fs_42", "fs_43", "fs_44", "fs_45","fs_46", "fs_47", "fs_48", "fs_49", "fs_50", "fs_51",
"fs_52", "fs_53"]

filepath_DSCOVR: '/Users/jl/Documents/Projects/SV-NASA/database/DSCOVR_PlasMAG/'
output_filename: 'db_Plasma_2016-2023.csv'
############################## MADRIGAL PARAMS #########################
# Madrigal Paramters
user_fullname : 'Jorge+Fernando+Lozano+Fernandez'
user_email : 'jorge.fernando.lozano@gmail.com'
user_afiliation: 'Bee3LabTech'
web_madrigal: 'http://cedar.openmadrigal.org'
#web_madrigal: 'http://madrigal.haystack.mit.edu'
instrument_code : '8100'
params: 'YEAR,MONTH,DAY,HOUR,MIN,SEC,KP,DST,AP,F10.7'
output_filename_mad: '/Users/jl/Documents/Projects/SV-NASA/database/MADRIGAL/db_Madrigal_test'
start_date: '09/29/2023'
end_date: '09/30/2023'
########################################################################
# CASSIOPE Parameters
input_filename_cass: '/Users/jl/Documents/Projects/SV-NASA/database/CASSIOPE/data80/'
output_filename_cass: '/Users/jl/Documents/Projects/SV-NASA/database/CASSIOPE/Data_Cassiope/'
settings_target: 'KP'
settings_target_value: 80
params_cass :
- [['batt_curr_time','batt_curr'],['batt_volt_time','batt_volt'],['certo_curr_time','certo_curr'],['fai_curr_time','fai_curr'],
        ['gap_curr_time','gap_curr'],['irm_curr_time','irm_curr'],['mag_a_curr_time','mag_a_curr'],['mag_b_curr_time','mag_b_curr'],
        ['mgf_curr_time','mgf_curr'],['mgf_boom_temp_time','mgf_boom_temp'],['mgf_box_temp_time','mgf_box_temp'],['nms_curr_time','nms_curr'],
        ['rri_curr_time','rri_curr'],['rri_temp_time','rri_temp'],['rx_a_curr_time','rx_a_curr'],['rx_b_curr_time','rx_b_curr'],
        ['sei_curr_time','sei_curr'],['slr_1_volt_time','slr_1_volt'],['slr_2_volt_time','slr_2_volt'],['slr_3_volt_time','slr_3_volt'],
        ['slr_4_volt_time','slr_4_volt'],['slr_curr_time','slr_curr'],['ss_a_curr_time','ss_a_curr'],['ss_b_curr_time','ss_b_curr'],
        ['tr_cmdtrq_x_time','tr_cmdtrq_x'],['tr_cmdtrq_y_time','tr_cmdtrq_y'],['tr_cmdtrq_z_time','tr_cmdtrq_z'],['tx_a_curr_time','tx_a_curr'],['tx_b_curr_time','tx_b_curr']]
########################################################################
# Data Integrations beteween CASSIOPE and DSCOVR DataSets
PATH_FILE_CASS : '/Users/jl/Documents/Projects/SV-NASA/database/CASSIOPE/Data_Cassiope/'
PATH_OUTPUT: 'datasetsml2024_short/'
TIME_DELTA : '20min'
PATH_FILE : '/Users/jl/Documents/Projects/SV-NASA/database/DSCOVR_PlasMAG/db_Plasma_2022-2023.csv'
############################DATA ENGINEERING AND TRAINING############################
# Data Engineering and Training
TARGET_ML : 'KP'
PATH_DATASET : 'datasetsml2024_short/MLDataSet_batt_curr.csv'
DROP_COLUMNS : [0,-2,-3] 
PATH_OUTPUT_TRAINING : 'training_output2024'
PATH_MODELS : 'models'